class_name NetworkConstants
extends RefCounted

const DEFAULT_PORT := 51873
const MAX_ENET_CLIENTS := 4095
const MAX_PLAYERS := MAX_ENET_CLIENTS + 1
const INPUT_SEND_HZ := 20.0
const SNAPSHOT_SEND_HZ := 15.0
const REMOTE_INTERPOLATION_SEC := 0.1
const HEARTBEAT_SEND_INTERVAL_SEC := 1.0
const HEARTBEAT_TIMEOUT_SEC := 8.0
const LAN_DISCOVERY_GAME_ID := "shooter_v1"
const LAN_DISCOVERY_PROTOCOL_VERSION := 1
const LAN_DISCOVERY_MULTICAST_GROUP := "239.192.43.21"
const LAN_DISCOVERY_BROADCAST_ADDRESS := "255.255.255.255"
const LAN_DISCOVERY_PORT := 51874
const LAN_DISCOVERY_ADVERTISE_INTERVAL_SEC := 1.0
const LAN_DISCOVERY_HOST_TIMEOUT_SEC := 4.0
